/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */
export const GITHUB_USER_FETCH = 'GITHUB_USER_FETCH';
export const GET_DEPARTAMENTOS = 'GET_DEPARTAMENTOS';
export const GET_ESTABLECIMIENTOS = 'GET_ESTABLECIMIENTOS';
export const GET_ESTABLECIMIENTOS_FETCH_DONE = 'GET_ESTABLECIMIENTOS_FETCH_DONE';
export const GET_DEPARTAMENTOS_FETCH_DONE = 'GET_DEPARTAMENTOS_FETCH_DONE';
export const GET_CLASE_PARTOS = 'GET_CLASE_PARTOS';
export const GET_CLASE_PARTOS_FETCH_DONE = 'GET_CLASE_PARTOS_FETCH_DONE';
export const GET_MUNICIPIOS = 'GET_MUNICIPIOS';
export const GET_MUNICIPIOS_FETCH_DONE = 'GET_MUNICIPIOS_FETCH_DONE';
export const GET_TIPO_DOCUMENTOS = 'GET_TIPO_DOCUMENTOS';
export const GET_TIPO_DOCUMENTOS_FETCH_DONE = 'GET_TIPO_DOCUMENTOS_FETCH_DONE';
export const GET_LOCAL_PARTOS = 'GET_LOCAL_PARTOS';
export const GET_LOCAL_PARTOS_FETCH_DONE = 'GET_LOCAL_PARTOS_FETCH_DONE';
